name: InvisibleLights
main: com.lith.invisiblelights.Plugin

version: 0.0.2
api-version: 1.20

description: A MineCraft plugin for TPA
author: Lith
website: https://github.com/ImLith/MC-Tpa

depend: [LithCore]
softdepend: []

commands:
  lightReload:
    description: Reload configs
    usage: /<command>
    permission: invislight.reload

permissions:
  invislight.reload:
    description: Reload configs
    default: op
