name: InvisibleLights
main: com.lith.invisiblelights.Plugin

version: 0.0.1
api-version: 1.20

description: A MineCraft plugin for TPA
author: Lith
website: https://github.com/ImLith/MC-Tpa

depend: [LithCore]
softdepend: []
